ktor:
  application:
    modules:
      - com.miaoyongzheng.ApplicationKt.module
  deployment:
    port: 8080
  development: true
jwt:
  domain: "https://miaoyongzheng.com/"
  secret: "miaoyongzheng-secret"
  audience: "miaoyongzheng-audience"
  issuer: "miaoyongzheng-issuer"
  realm: "miaoyongzheng-realm"
mysql:
  url: "jdbc:mysql://localhost:3306/medintel"
  username: "root"
  password: "123456"
  driver: "com.mysql.cj.jdbc.Driver"
redis:
  host: "http://localhost"
  port: 6379
